// Generated by CoffeeScript 1.12.4
var Event, EventType, NamedFunction, Type, assertType;

NamedFunction = require("NamedFunction");

assertType = require("assertType");

Type = require("Type");

Event = require("./Event");

EventType = NamedFunction("EventType", function(name, config) {
  var argTypes, isAsync, type;
  if (arguments.length === 1) {
    config = name;
    name = void 0;
  }
  assertType(name, String.Maybe);
  assertType(config, Object);
  type = Type(name);
  type.inherits(Event);
  type.createArgs(function(args) {
    var options;
    if (!(options = args[0])) {
      args[0] = options = {};
    }
    return args;
  });
  if (argTypes = config.argTypes) {
    assertType(argTypes, Object);
    type.createArgs(function(args) {
      args[0].argTypes = argTypes;
      return args;
    });
  }
  if (config.async != null) {
    isAsync = config.async;
    type.createArgs(function(args) {
      args[0].async = isAsync;
      return args;
    });
  }
  return type.build();
});

module.exports = EventType;
